import Head from "next/head";
import styles from "../../styles/Home.module.css";

import styled from "styled-components";

export const Container = styled.div`
  grid-area: main;
  background-color: lightblue;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      main
    </Container>
  );
}
