import Head from "next/head";
import styles from "../../styles/Home.module.css";

import styled from "styled-components";
import { AuthContext } from "../provider/context";
import { useContext, useState } from "react";
import Main from "../components/Main";

export const Container = styled.div`
  grid-area: main;
  background-color: lightblue;
`;

export default function Home() {
  const { info, items } = useContext(AuthContext);
  console.log(items);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main info={info}></Main>
    </Container>
  );
}
